image:
  - Visual Studio 2019
#  - Ubuntu
#  - macOS
  
branches:
  only:
    - master

environment:
  matrix:
    - nodejs_version: "12" # lts
  DEBUG: "*"

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install -g npm@latest
  - npm install

test_script:
  - npm run-script testci

build: off
